Exercicio 01
NickolasLuan/Exercicios-Bootcamp pull request #1
Opened 2023-10-08 16:32 UTC by NickolasLuan

Estou entregando o exercício 1 para o code-review dos mentores.

2023-10-09 22:24 UTC, arthurpaesrizon requested changes

2023-10-09 22:24 UTC, arthurpaesrizon commented on src/Exercicio1.ts
> +function ContarVogais(palavra: string){
Podes tipar o retorno da função
Também é bom seguir o padrão de camelCase para nomear funções e começar com a letra minúscula.
Ficaria: contarVogais

2023-10-09 22:24 UTC, arthurpaesrizon commented on src/Exercicio1.ts
> +    let qtdVogais = 0;
Consegues tipar as variáveis também

2023-10-09 22:24 UTC, arthurpaesrizon commented on src/Exercicio1.ts
> +    const vogais = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"];
Não é necessário um array com minúsculas e maiúsculas. Podes apenas utilizar algo como toLowerCase() pra forçar tudo para minúsculo. 
Também poderias fazer a verificação de vogais com acento.

2023-10-10 00:51 UTC, NickolasLuan commented
Mudei meu código utilizando uma expressão regular para validar vogais com acentos e utilizei o toLowerCase para transformar as palavras em minusculas.

2023-10-11 02:28 UTC, arthurpaesrizon approved these changes

2023-10-11 02:29 UTC, merged